# Generated by Django 6.1.1 on 2026-10-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="code",
            field=models.CharField(
                choices=[
                    ("CREDIT_1", "1 Crédit"),
                    ("CREDIT_5", "5 Crédits"),
                    ("CREDIT_25", "25 Crédits"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
