# Generated by Django 6.1 on 2026-08-16 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("URL", "Lien URL"),
                            ("PDF", "Fichier PDF"),
                            ("TEXT", "Texte Brut"),
                        ],
                        default="TEXT",
                        max_length=10,
                    ),
                ),
                ("source_url", models.URLField(blank=True, null=True)),
                (
                    "source_file",
                    models.FileField(blank=True, null=True, upload_to="jobs/sources/"),
                ),
                ("raw_text", models.TextField(blank=True, default="")),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("company", models.CharField(blank=True, default="", max_length=255)),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                (
                    "site_category",
                    models.CharField(blank=True, default="acpe", max_length=100),
                ),
                (
                    "abbreviation",
                    models.CharField(blank=True, default="POSTE", max_length=100),
                ),
                ("cleaned_description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_offers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cv_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="applications/cv/"
                    ),
                ),
                (
                    "cover_letter_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="applications/lm/"
                    ),
                ),
                (
                    "email_txt",
                    models.FileField(
                        blank=True, null=True, upload_to="applications/email/"
                    ),
                ),
                (
                    "offer_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="applications/offer/"
                    ),
                ),
                (
                    "zip_package",
                    models.FileField(
                        blank=True, null=True, upload_to="applications/zip/"
                    ),
                ),
                (
                    "email_subject",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("email_body", models.TextField(blank=True, default="")),
                (
                    "folder_path",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="jobs.joboffer",
                    ),
                ),
            ],
        ),
    ]
