# Generated by Django 6.1 on 2026-08-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationpackage",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("approuved", "Approuvé"),
                    ("pending", "En attente"),
                    ("failed", "Échoué"),
                ],
                default="approuved",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="applicationpackage",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("finalized", "Finalisé"),
                    ("pending", "En attente"),
                    ("inprocess", "En traitement"),
                ],
                default="finalized",
                max_length=20,
            ),
        ),
    ]
