# Generated by Django 6.1.1 on 2026-10-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_applicationpackage_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationpackage",
            name="cv_text",
            field=models.TextField(
                blank=True, default="", help_text="Texte du CV généré par Ollama LLM"
            ),
        ),
        migrations.AddField(
            model_name="applicationpackage",
            name="email_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Texte de l'Email généré par Ollama LLM",
            ),
        ),
        migrations.AddField(
            model_name="applicationpackage",
            name="lm_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Texte de la LM générée par Ollama LLM",
            ),
        ),
    ]
