# Generated by Django 6.1.1 on 2026-10-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_applicationpackage_cv_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="joboffer",
            name="language",
            field=models.CharField(
                choices=[
                    ("fr", "Français"),
                    ("en", "English"),
                    ("ar", "العربية"),
                    ("pt", "Português"),
                    ("es", "Español"),
                    ("sw", "Kiswahili"),
                    ("zh", "中文"),
                ],
                default="fr",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="applicationpackage",
            name="cv_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Texte du CV généré par Groq Cloud API LLM",
            ),
        ),
        migrations.AlterField(
            model_name="applicationpackage",
            name="email_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Texte de l'Email généré par Groq Cloud API LLM",
            ),
        ),
        migrations.AlterField(
            model_name="applicationpackage",
            name="lm_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Texte de la LM générée par Groq Cloud API LLM",
            ),
        ),
    ]
