# Generated by Django 6.1 on 2026-08-16 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="Consultant IT & Expert Fullstack",
                        max_length=255,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="+242 06 613 01 18", max_length=50
                    ),
                ),
                (
                    "cities",
                    models.CharField(
                        blank=True,
                        default="Brazzaville & Pointe-Noire, Congo",
                        max_length=255,
                    ),
                ),
                (
                    "github_url",
                    models.URLField(blank=True, default="https://github.com"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, default="https://linkedin.com"),
                ),
                ("readme_content", models.TextField(blank=True, default="")),
                (
                    "original_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="profiles/original/"
                    ),
                ),
                (
                    "cropped_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="profiles/cropped/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
