# Generated by Django 6.1 on 2026-08-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_manager", "0002_certification_education_experience_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofileinfo",
            name="adressepay",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
