# Generated by Django 6.1 on 2026-08-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_manager", "0003_userprofileinfo_adressepay"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofileinfo",
            name="adressepay",
        ),
        migrations.AddField(
            model_name="userprofileinfo",
            name="country",
            field=models.CharField(blank=True, default="Congo", max_length=100),
        ),
    ]
