# Generated by Django 6.1.1 on 2026-10-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_manager", "0004_remove_userprofileinfo_adressepay_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="photo_base64",
            field=models.TextField(
                blank=True, default="", help_text="Photo de profil encodée en Base64"
            ),
        ),
    ]
