# Generated by Django 6.1.1 on 2026-10-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_manager", "0005_profile_photo_base64"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="photo_base64",
        ),
        migrations.AddField(
            model_name="profile",
            name="cropped_photo_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL Cloudinary de la photo recadrée",
                max_length=1000,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="original_photo_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL Cloudinary de la photo originale",
                max_length=1000,
            ),
        ),
    ]
